include: package:all_lint_rules_community/all.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
    
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    - "analysis_options.yaml"
  

linter:
  rules:
    always_specify_types: false
    always_use_package_imports: false
    prefer_double_quotes: false
    prefer_final_parameters: false
    sort_constructors_first: false
    type_annotate_public_apis: false
    unnecessary_final: false

    

# Uncomment the following section to specify additional rules.

# linter:
#   rules:
#     - camel_case_types

# analyzer:
#   exclude:
#     - path/to/excluded/files/**

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
