name: vlsid
description: This is a variable length sortable id generator.
version: 2.0.0
homepage: https://github.com/fbede/vlsid

topics:
  - id
  - uuid
  - identifier
  - sortable-id
  - nano-id

environment:
  sdk: '>=2.17.5 <4.0.0'

dev_dependencies:
  all_lint_rules_community: ^0.0.40
  test: ^1.16.0

