name: vlsid
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/fbede/vlsid
environment:
  sdk: '>=2.17.5 <4.0.0'

dev_dependencies:
  all_lint_rules_community: ^0.0.40
  test: ^1.16.0

